---
- name: configure virtualhost
  gather_facts: false
  hosts: apache-servers
  become: true
  tasks:
   - name: Configure  virtualhost 
     template:
      src: templ/vhosts.j2
      dest: "/etc/httpd/conf.d/{{ item.name }}.conf"
     loop: "{{ sites }}"
     notify: Restart HTTPD

  handlers:
   - name: Restart HTTPD
     service:
      name: httpd
      state: restarted

