---
- name: configure nginx
  hosts: nginx-servers
  become: true 
  gather_facts: false 
  tasks:
    - name: set httpd_can_nestwork_connect 
      seboolean:
        name: httpd_can_network_connect
        state: true
        persistent: true

    - name: configure backend
      template:
        src: templ/backend.j2
        dest: "/etc/nginx/conf.d/backend.conf"
      notify: Restart Nginx
    - name : configure proxy
      template:
        src: templ/proxy.j2
        dest: "/etc/nginx/default.d/proxy.conf"
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx 
      service:
        name: nginx
        state: restarted

