---
- name: install nginx
  hosts: nginx-servers
  become: true
  gather_facts: false
  tasks:
    - name: install nginx-server
      yum:
        name:  nginx
        state: latest
 
    - name: start service
      service:
        name: nginx.service
        enabled: true
        state: started 

